/* Bindings typescript generated by archetype version: 1.2.14 */

import { registerEvent, WellEvent, WellEventData, WellEventProcessor } from '@completium/event-well-crank';

/* Event: SwitchOn */

export interface SwitchOn extends WellEvent {

}

const is_SwitchOn = (typ : string) : boolean => {
  return typ === 'SwitchOn'
}

const handle_SwitchOn = (handler : WellEventProcessor<SwitchOn>) => (event : any, data ?: WellEventData) => {
  handler({ }, data)
}

export function register_SwitchOn(source : string, handler : WellEventProcessor<SwitchOn>) {
  registerEvent({ source: source, filter : is_SwitchOn, process: handle_SwitchOn(handler) })
}


/* Event: SwitchOff */

export interface SwitchOff extends WellEvent {

}

const is_SwitchOff = (typ : string) : boolean => {
  return typ === 'SwitchOff'
}

const handle_SwitchOff = (handler : WellEventProcessor<SwitchOff>) => (event : any, data ?: WellEventData) => {
  handler({ }, data)
}

export function register_SwitchOff(source : string, handler : WellEventProcessor<SwitchOff>) {
  registerEvent({ source: source, filter : is_SwitchOff, process: handle_SwitchOff(handler) })
}
